<?php
//About Banner
return array(
	'name'             => esc_html__( 'About With Info Box 2', 'ciyashop' ),
	'template_category'=> esc_html__( 'About', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
<p>[vc_row full_width="stretch_row" equal_height="yes" content_placement="middle" el_id="1533298091712-0962df14-f3e0" css=".vc_custom_1533795238192{padding-top: 60px !important;padding-bottom: 90px !important;background-color: #fbf7f6 !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-6"][vc_custom_heading text="Why Choose Us?" use_theme_fonts="yes"][vc_column_text css=".vc_custom_1533644905076{margin-top: 10px !important;margin-bottom: 30px !important;}"]I truly believe Augustine’s words are true and if you look at history you know it is true. There are many people in the world with amazing talents who realize only a small percentage of their potential.[/vc_column_text][mpc_icon_column preset="mpc_preset_10" layout="style_3" alignment="left" padding_css="padding:0px;" title_font_preset="preset_0" title_font_color="#444444" title_font_size="20" title_font_line_height="1.4" title_font_transform="none" title_font_align="left" title="100% Pure Leather" title_margin_divider="true" title_margin_css="margin-left:30px;" content_font_preset="preset_0" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" content_margin_divider="true" content_margin_css="margin-left:30px;" mpc_icon__icon_type="image" mpc_icon__icon_image="488" mpc_icon__border_css="border-radius:0px;" mpc_icon__padding_divider="true" mpc_icon__padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-top:0px;margin-right:0px;" mpc_icon__hover_icon_color="#ffffff" mpc_icon__hover_background_color="#275a7a" mpc_icon__hover_border_css="border-radius:0px;" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__align="left" mpc_divider__content_padding_divider="true" mpc_divider__content_padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_divider__lines_color="#dddddd" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:3px;padding-bottom:3px;"]Commitment – understanding the price<br />
and having the willingness to pay that price[/mpc_icon_column][vc_empty_space height="40px"][mpc_icon_column preset="mpc_preset_10" layout="style_3" alignment="left" padding_css="padding:0px;" title_font_preset="preset_0" title_font_color="#444444" title_font_size="20" title_font_line_height="1.4" title_font_transform="none" title_font_align="left" title="Free Delivery" title_margin_divider="true" title_margin_css="margin-left:30px;" content_font_preset="preset_0" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" content_margin_divider="true" content_margin_css="margin-left:30px;" mpc_icon__icon_type="image" mpc_icon__icon_image="489" mpc_icon__border_css="border-radius:0px;" mpc_icon__padding_divider="true" mpc_icon__padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-top:0px;margin-right:0px;" mpc_icon__hover_icon_color="#ffffff" mpc_icon__hover_background_color="#275a7a" mpc_icon__hover_border_css="border-radius:0px;" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__align="left" mpc_divider__content_padding_divider="true" mpc_divider__content_padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_divider__lines_color="#dddddd" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:3px;padding-bottom:3px;"]Printin k a of type and lorem Ipsum<br />
is simply dummy text of the galley[/mpc_icon_column][vc_empty_space height="40px"][mpc_icon_column preset="mpc_preset_10" layout="style_3" alignment="left" padding_css="padding:0px;" title_font_preset="preset_0" title_font_color="#444444" title_font_size="20" title_font_line_height="1.4" title_font_transform="none" title_font_align="left" title="High Quality Product" title_margin_divider="true" title_margin_css="margin-left:30px;" content_font_preset="preset_0" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" content_margin_divider="true" content_margin_css="margin-left:30px;" mpc_icon__icon_type="image" mpc_icon__icon_image="490" mpc_icon__border_css="border-radius:0px;" mpc_icon__padding_divider="true" mpc_icon__padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-top:0px;margin-right:0px;" mpc_icon__hover_icon_color="#ffffff" mpc_icon__hover_background_color="#275a7a" mpc_icon__hover_border_css="border-radius:0px;" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__align="left" mpc_divider__content_padding_divider="true" mpc_divider__content_padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_divider__lines_color="#dddddd" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:3px;padding-bottom:3px;"]Text of the printin lorem ipsum the<br />
is simply k a type text and galley of[/mpc_icon_column][/vc_column][vc_column offset="vc_col-lg-6 vc_col-md-6"][vc_single_image source="external_link" alignment="center" custom_src="http://ciyashop.potenzaglobalsolutions.com/leather/wp-content/uploads/sites/28/2018/08/why-choose.png"][/vc_column][/vc_row]</p>
CONTENT
);