<?php
//About Banner
return array(
	'name'             => esc_html__( 'About Jewellery with Image', 'ciyashop' ),
	'template_category'=> esc_html__( 'About', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row equal_height="yes" content_placement="middle" pgscore_enable_responsive_settings="true" el_id="1515049021805-83a2d73e-3dc8" css=".vc_custom_1524045923721{padding-top: 40px !important;padding-bottom: 40px !important;}" element_css_md=".vc_custom_1524045923726{padding-top: 30px !important;padding-bottom: 30px !important;}" element_css_sm=".vc_custom_1524045923730{padding-top: 20px !important;padding-bottom: 20px !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-6" css=".vc_custom_1524045687205{padding-top: 0px !important;}"][vc_single_image source="external_link" alignment="center" custom_src="http://ciyashop.potenzaglobalsolutions.com/jewellery/wp-content/uploads/2018/01/01.png"][/vc_column][vc_column css=".vc_custom_1524045836284{margin-top: 30px !important;margin-bottom: 30px !important;padding-top: 0px !important;}" offset="vc_col-lg-6 vc_col-md-6"][vc_custom_heading text="Jewellery For You" use_theme_fonts="yes" font_weight="600" css=".vc_custom_1515062580806{margin-bottom: 15px !important;}"][vc_column_text]There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
<p>If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary.[/vc_column_text][pgscore_list add_icon="true" list_items="%5B%7B%22content%22%3A%22But%20I%20must%20explain%20to%20you%20how%20all%20this%20mistaken%20idea%22%7D%2C%7B%22content%22%3A%22But%20who%20has%20any%20right%20to%20find%20fault%20with%20a%20man%20who%20chooses%22%7D%2C%7B%22content%22%3A%22But%20in%20certain%20circumstances%20and%20owing%20to%20the%20claims%22%7D%2C%7B%22content%22%3A%22Ut%20enim%20ad%20minima%20veniam%22%7D%5D" element_css=".vc_custom_1515051282141{margin-bottom: 20px !important;}" element_id="" element_class="" icon_type="fontawesome" icon_fontawesome="fa fa-check" icon_openiconic="vc-oi vc-oi-dial" icon_typicons="typcn typcn-adjust-brightness" icon_entypo="entypo-icon entypo-icon-note" icon_linecons="" icon_monosocial="vc-mono vc-mono-fivehundredpx" icon_material="vc-material vc-material-cake" icon_pixelicons="vc_pixel_icon vc_pixel_icon-alert"][mpc_button preset="preset_192" url="url:http%3A%2F%2Fthemes.potenzaglobalsolutions.com%2Fciya-shop%2Fjewellery%2Fshop%2F|title:Link||" font_preset="default" font_color="#ffffff" font_size="13" font_line_height="1.6" font_transform="uppercase" font_align="inherit" title="Read More" background_color="#ccb883" border_divider="true" border_css="border-radius:3px;" padding_divider="true" padding_css="padding-top:12px;padding-right:30px;padding-bottom:12px;padding-left:30px;" margin_divider="true" margin_css="margin-top:6px;margin-right:10px;margin-bottom:4px;margin-left:10px;" hover_font_color="#ffffff" hover_icon_color="#0a0404" hover_background_color="#323232" hover_border_divider="true" mpc_tooltip__border_divider="true" mpc_tooltip__padding_divider="true"][/vc_column][/vc_row]
CONTENT
);