<?php
//About Banner
return array(
	'name'             => esc_html__( 'About with Kids Category', 'ciyashop' ),
	'template_category'=> esc_html__( 'About', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row pgscore_enable_responsive_settings="true" el_id="1518529007436-199b93d3-fa02" css=".vc_custom_1524471135606{margin-top: 80px !important;margin-bottom: 80px !important;}" element_css_md=".vc_custom_1524471135607{margin-top: 60px !important;margin-bottom: 60px !important;}" element_css_sm=".vc_custom_1524471135608{margin-top: 50px !important;margin-bottom: 50px !important;}" element_css_xs=".vc_custom_1524471135613{margin-top: 40px !important;margin-bottom: 40px !important;}"][vc_column][vc_custom_heading text="Welcome to Ciya Kids" font_container="tag:h4|text_align:left" use_theme_fonts="yes" font_weight="700" text_transform="uppercase" css=".vc_custom_1518529065884{margin-bottom: 15px !important;}"][vc_custom_heading text="Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincidunt ut laoree Dolore magna aliquam erat volutpat." font_container="tag:h6|text_align:left|line_height:1.5em" use_theme_fonts="yes" font_weight="400"][vc_custom_heading text="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab voluptas consectetur laboriosam vero, dolores nisi quod neque fugiat, excepturi nihil non, rerum porro iusto commodi. Ea repellat perspiciatis, reiciendis ullam tempore facere corporis, blanditiis deserunt placeat optio officiis nostrum voluptas labore expedita explicabo molestiae. Enim optio, dolorum." font_container="tag:p|text_align:left" use_theme_fonts="yes" css=".vc_custom_1524471107766{margin-bottom: 25px !important;}"][mpc_wc_carousel_categories carousel_preset="mpc_preset_9" rows="1" cols="4" gap="20" start_at="1" loop="true" orderby="title" order="DESC" height="349" effect="stay" fx_effect="zoomIn" fx_scale="107" border_css="border-width:1px;border-color:#e8e8e8;border-style:solid;" title_font_color="#323232" title_font_size="18" title_font_line_height="1.5" title_font_transform="capitalize" title_font_align="center" background_color="#ffffff" regular_padding_divider="true" regular_padding_css="padding-top:15px;padding-bottom:15px;" hover_title_font_color="#225eb9" hover_title_font_size="18" hover_title_font_line_height="1.5" hover_title_font_transform="capitalize" hover_title_font_align="center" overlay_background_color="rgba(255,255,255,0.32)" hover_background_fullfill="true" overlay_padding_divider="true" overlay_padding_css="padding-top:15px;padding-bottom:15px;" mpc_navigation__preset="preset_0" include="73, 74, 82, 83, 84, 81, 80"][/vc_column][/vc_row]
CONTENT
);