<?php
//About Banner
return array(
	'name'             => esc_html__( 'About Left Style 2', 'ciyashop' ),
	'template_category'=> esc_html__( 'About', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row equal_height="yes" content_placement="middle" pgscore_enable_responsive_settings="true" el_id="1517476366799-240455d7-735e" css=".vc_custom_1517567421643{padding-top: 80px !important;padding-bottom: 50px !important;}" element_css_md=".vc_custom_1517567421649{padding-top: 60px !important;padding-bottom: 30px !important;}" element_css_sm=".vc_custom_1517567421653{padding-top: 50px !important;padding-bottom: 20px !important;}" element_css_xs=".vc_custom_1517567421658{padding-top: 40px !important;padding-bottom: 10px !important;}"][vc_column css=".vc_custom_1517552957475{padding-top: 0px !important;}" offset="vc_col-lg-6 vc_col-md-6"][vc_row_inner][vc_column_inner css=".vc_custom_1517476876302{margin-bottom: 30px !important;}"][vc_single_image source="external_link" custom_src="http://ciyashop.potenzaglobalsolutions.com/goggles/wp-content/uploads/2018/02/about-img1.jpg"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/2" css=".vc_custom_1517478407509{margin-bottom: 30px !important;}"][vc_single_image source="external_link" custom_src="http://ciyashop.potenzaglobalsolutions.com/goggles/wp-content/uploads/2018/02/about-img3.jpg"][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1517478423275{margin-bottom: 30px !important;}"][vc_single_image source="external_link" custom_src="http://ciyashop.potenzaglobalsolutions.com/goggles/wp-content/uploads/2018/02/about-img2.jpg"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column css=".vc_custom_1517552966748{margin-bottom: 30px !important;padding-top: 0px !important;}" offset="vc_col-lg-6 vc_col-md-6"][vc_custom_heading text="What we do the best" font_container="tag:h3|text_align:left" use_theme_fonts="yes" font_weight="700" css=".vc_custom_1517567179196{margin-bottom: 15px !important;}"][vc_column_text]<strong>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, scrambled it to make a type specimen book.</strong></p>
<p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with passages, and more recently with desktop publishing software. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.[/vc_column_text][mpc_progress preset="mpc_preset_9" value="82" thickness="5" background_color="#f5f5f5" border_divider="true" border_css="border-radius:3px;" border_radius="3" padding_divider="true" margin_divider="true" title_font_color="#323232" title_font_size="14" title_font_line_height="1.3" title_font_transform="none" title_font_align="left" title="Modern goggles Design" title_padding_divider="true" title_padding_bottom="10" title_padding_css="padding-bottom:10px;" value_font_color="#f53d03" value_font_line_height="1.3" value_number="82" value_padding_divider="true" value_padding_bottom="10" value_padding_css="padding-bottom:10px;" progress_background_color="#f53d03" progress_border_divider="true" progress_border_css="border-radius:3px;" progress_border_radius="3"][mpc_progress preset="mpc_preset_9" value="62" thickness="5" background_color="#f5f5f5" border_divider="true" border_css="border-radius:3px;" border_radius="3" padding_divider="true" margin_divider="true" title_font_color="#323232" title_font_size="14" title_font_line_height="1.3" title_font_transform="none" title_font_align="left" title="Goggles Online Shopping" title_padding_divider="true" title_padding_bottom="10" title_padding_css="padding-bottom:10px;" value_font_color="#f53d03" value_font_line_height="1.3" value_number="62" value_padding_divider="true" value_padding_bottom="10" value_padding_css="padding-bottom:10px;" progress_background_color="#f53d03" progress_border_divider="true" progress_border_css="border-radius:3px;" progress_border_radius="3"][mpc_progress preset="mpc_preset_9" value="84" thickness="5" background_color="#f5f5f5" border_divider="true" border_css="border-radius:3px;" padding_divider="true" padding_css="padding-bottom:0px;" margin_divider="true" title_font_color="#323232" title_font_size="14" title_font_line_height="1.3" title_font_transform="none" title_font_align="left" title="Shipping & Reselling" title_padding_divider="true" title_padding_css="padding-bottom:10px;" value_font_color="#f53d03" value_font_line_height="1.3" value_number="84" value_padding_divider="true" value_padding_css="padding-bottom:10px;" progress_background_color="#f53d03" progress_border_divider="true" progress_border_css="border-radius:3px;"][/vc_column][/vc_row]
CONTENT
);