<?php
//About Banner
return array(
	'name'             => esc_html__( 'About with Accordion', 'ciyashop' ),
	'template_category'=> esc_html__( 'About', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row full_width="stretch_row" pgscore_enable_responsive_settings="true" el_id="1521705241371-4bb3f414-6c18" css=".vc_custom_1521725090970{padding-top: 80px !important;padding-bottom: 80px !important;background-image: url(http://ciyashop.potenzaglobalsolutions.com/auto-parts/wp-content/uploads/sites/9/2018/03/09-2.jpg?id=616) !important;}" element_css_md=".vc_custom_1521725090973{padding-top: 60px !important;padding-bottom: 60px !important;}" element_css_sm=".vc_custom_1521725090976{padding-top: 50px !important;padding-bottom: 50px !important;}" element_css_xs=".vc_custom_1521725090979{padding-top: 40px !important;padding-bottom: 40px !important;}" el_class="bg-img-remove "][vc_column width="1/2" offset="vc_col-lg-6 vc_hidden-md vc_hidden-sm vc_hidden-xs"][/vc_column][vc_column css=".vc_custom_1521725148190{padding-top: 0px !important;}" offset="vc_col-lg-6 vc_col-md-12 vc_col-xs-12"][vc_row_inner][vc_column_inner][vc_custom_heading text="Frequently Asked Questions." font_container="tag:h3|text_align:left" use_theme_fonts="yes" font_weight="bold" text_transform="uppercase"][mpc_divider preset="mpc_preset_5" width="30" align="left" content_type="icon" content_position="25" icon="ti ti-dashboard" icon_color="#e01f22" icon_size="30" lines_style="dashed" lines_color="#e01f22" lines_weight="2" margin_divider="true"][/vc_column_inner][/vc_row_inner][vc_tta_accordion style="flat" shape="square" color="white" c_position="right" active_section="1" css=".vc_custom_1524484361377{margin-top: 20px !important;}"][vc_tta_section title="1. Do you service hybrid vehicles?" tab_id="1521705242414-fef5c2e1-7a7bc302-fe82"][vc_column_text]I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

[/vc_column_text][/vc_tta_section][vc_tta_section i_type="flaticon" i_icon_flaticon="glyph-icon pgsicon-ecommerce-leftwards-pointer" title="2. What does an annual service include?" tab_id="1521705242505-0b0b8496-8a5ec302-fe82"][vc_column_text]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.

[/vc_column_text][/vc_tta_section][vc_tta_section i_type="flaticon" i_icon_flaticon="glyph-icon pgsicon-ecommerce-leftwards-pointer" title="3. Do you use high quality parts?" tab_id="1521706245562-57fb2b5a-9a2bc302-fe82"][vc_column_text]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.

[/vc_column_text][/vc_tta_section][/vc_tta_accordion][/vc_column][/vc_row]
CONTENT
);