<?php
//About Banner
return array(
	'name'             => esc_html__( 'About Skill Left Parallax', 'ciyashop' ),
	'template_category'=> esc_html__( 'About', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row full_width="stretch_row_content_no_spaces" equal_height="yes" content_placement="middle" pgscore_background_position="left-center" el_id="1508152783836-f8904e30-b78d"][vc_column parallax="content-moving" parallax_image="9678" css=".vc_custom_1513589437946{padding-top: 50% !important;padding-bottom: 50% !important;}" offset="vc_col-lg-6 vc_col-md-6"][/vc_column][vc_column offset="vc_col-lg-6 vc_col-md-6" css=".vc_custom_1524030863159{padding-top: 30px !important;padding-right: 10% !important;padding-bottom: 30px !important;padding-left: 10% !important;}"][vc_custom_heading text="Discover the best collection for autumn of Stylist Art" font_container="tag:h3|text_align:left|line_height:1.3em" use_theme_fonts="yes" font_weight="700" css=".vc_custom_1524030888711{margin-top: 20px !important;margin-bottom: 15px !important;}"][vc_column_text]At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.</p>
<p>These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted.[/vc_column_text][mpc_progress preset="mpc_preset_10" value="60" thickness="5" background_color="#f5f5f5" title_font_size="16" title_font_line_height="1.3" title_font_transform="none" title_font_align="left" title="Online Shopping" title_padding_divider="true" title_padding_css="padding-bottom:10px;" value_font_line_height="1.3" value_number="60" value_padding_divider="true" value_padding_css="padding-bottom:10px;" progress_background_color="#04d39f"][mpc_progress preset="mpc_preset_10" value="85" thickness="5" background_color="#f5f5f5" title_font_size="16" title_font_line_height="1.3" title_font_transform="none" title_font_align="left" title="Online Shopping" title_padding_divider="true" title_padding_css="padding-bottom:10px;" value_font_line_height="1.3" value_number="85" value_padding_divider="true" value_padding_css="padding-bottom:10px;" progress_background_color="#04d39f"][mpc_progress preset="mpc_preset_10" value="70" thickness="5" background_color="#f5f5f5" title_font_size="16" title_font_line_height="1.3" title_font_transform="none" title_font_align="left" title="Online Shopping" title_padding_divider="true" title_padding_css="padding-bottom:10px;" value_font_line_height="1.3" value_number="70" value_padding_divider="true" value_padding_css="padding-bottom:10px;" progress_background_color="#04d39f"][mpc_progress preset="mpc_preset_10" value="40" thickness="5" background_color="#f5f5f5" title_font_size="16" title_font_line_height="1.3" title_font_transform="none" title_font_align="left" title="Online Shopping" title_padding_divider="true" title_padding_css="padding-bottom:10px;" value_font_line_height="1.3" value_number="40" value_padding_divider="true" value_padding_css="padding-bottom:10px;" progress_background_color="#04d39f"][/vc_column][/vc_row]
CONTENT
);