<?php
//About Banner
return array(
	'name'             => esc_html__( 'About with Magnific Popup', 'ciyashop' ),
	'template_category'=> esc_html__( 'About', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
	[vc_row content_placement="middle" pgscore_enable_responsive_settings="true" el_id="1519119724470-1560bc99-ed56" css=".vc_custom_1524472024832{margin-top: 80px !important;margin-bottom: 80px !important;}" element_css_md=".vc_custom_1524472024834{margin-top: 60px !important;margin-bottom: 60px !important;}" element_css_sm=".vc_custom_1524472024835{margin-top: 50px !important;margin-bottom: 50px !important;}" element_css_xs=".vc_custom_1524472024838{margin-top: 40px !important;margin-bottom: 40px !important;}"][vc_column offset="vc_col-lg-7 vc_col-md-6"][mpc_grid_images preset="mpc_preset_2" images="521,522" cols="2" gap="25" image_size="large" image_opacity="100" effect="none" effect_reverse="true" image_hover_opacity="100" overlay_background="rgba(174,75,92,0.5)" overlay_enable_lightbox="true" overlay_icon="ti ti-plus" overlay_icon_color="#ffffff" overlay_icon_size="30" overlay_url_icon="etl etl-attachment" overlay_url_icon_color="#ffffff" overlay_url_icon_size="48" overlay_icon_background="rgba(255,255,255,0.01)" overlay_icon_border_css="border-radius:100px;" overlay_icon_padding_css="padding:10px;" overlay_hover_color="#ae4b5c" overlay_hover_icon_background="#ffffff"][/vc_column][vc_column offset="vc_col-lg-5 vc_col-md-6"][vc_custom_heading text="Our History" font_container="tag:h2|text_align:left|color:%23ae4b5c" google_fonts="font_family:Playfair%20Display%3Aregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:400%20regular%3A400%3Anormal" css=".vc_custom_1524472309413{margin-bottom: 30px !important;}"][vc_column_text css=".vc_custom_1519448668816{margin-bottom: 0px !important;}"]Founded 45 years ago by a married couple of hobbyist florists from Florida, over the years this thing grew into one of the biggest flower shops in the local area.

With so many years of experience in taking care of, picking and arranging this many types of flowers into bouquets Nancy & John were bound for success.[/vc_column_text][/vc_column][/vc_row]
CONTENT
);