<?php
//About Banner
return array(
	'name'             => esc_html__( 'About with Counter', 'ciyashop' ),
	'template_category'=> esc_html__( 'About', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row full_width="stretch_row" equal_height="yes" content_placement="middle" el_id="1517631246054-57f82883-577b" css=".vc_custom_1524469715167{padding-top: 80px !important;padding-bottom: 50px !important;background-color: #f5f5f5 !important;}"][vc_column css=".vc_custom_1517644403914{padding-top: 0px !important;padding-bottom: 30px !important;}" el_class="order-lg-2" offset="vc_col-lg-6 vc_col-md-6"][vc_single_image source="external_link" custom_src="http://ciyashop.potenzaglobalsolutions.com/goggles/wp-content/uploads/2018/02/about-img.jpg"][/vc_column][vc_column css=".vc_custom_1524469813721{padding-top: 0px !important;}" el_class="order-lg-1" offset="vc_col-lg-6 vc_col-md-6"][vc_custom_heading text="Founded in 2017" font_container="tag:h3|text_align:left" use_theme_fonts="yes" font_weight="700" css=".vc_custom_1517635239297{margin-bottom: 15px !important;}"][vc_column_text]<strong>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</strong></p>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.[/vc_column_text][vc_row_inner][vc_column_inner width="1/3"][mpc_counter preset="mpc_preset_5" layout="style_2" alignment="left" title_font_color="#555555" title_font_size="16" title_font_line_height="1" title_font_transform="none" title="Online Sellings" counter_font_color="#f53d03" counter_font_size="40" counter_font_line_height="1.55" value="2050" duration="1750" delay="0" border_color="#f7f7f7" border_css="border-color:#f7f7f7;" mpc_icon__disable="true" mpc_icon__padding_divider="true" mpc_divider__disable="true" mpc_divider__width="60" mpc_divider__lines_color="#88d482" mpc_divider__lines_weight="8" mpc_divider__padding_divider="true" mpc_divider__padding_top="8" mpc_divider__padding_bottom="10" mpc_divider__padding_css="padding-top:8px;padding-bottom:10px;"][/vc_column_inner][vc_column_inner width="1/3"][mpc_counter preset="mpc_preset_5" layout="style_2" alignment="left" title_font_color="#555555" title_font_size="16" title_font_line_height="1" title_font_transform="none" title="Happy Clients" counter_font_color="#f53d03" counter_font_size="40" counter_font_line_height="1.55" value="1075" duration="1750" delay="0" border_color="#f7f7f7" border_css="border-color:#f7f7f7;" mpc_icon__disable="true" mpc_icon__padding_divider="true" mpc_divider__disable="true" mpc_divider__width="60" mpc_divider__lines_color="#88d482" mpc_divider__lines_weight="8" mpc_divider__padding_divider="true" mpc_divider__padding_top="8" mpc_divider__padding_bottom="10" mpc_divider__padding_css="padding-top:8px;padding-bottom:10px;"][/vc_column_inner][vc_column_inner width="1/3"][mpc_counter preset="mpc_preset_5" layout="style_2" alignment="left" title_font_color="#555555" title_font_size="16" title_font_line_height="1" title_font_transform="none" title="Award Winning" counter_font_color="#f53d03" counter_font_size="40" counter_font_line_height="1.55" value="170" duration="1750" delay="0" border_css="border-color:#f7f7f7;" mpc_icon__disable="true" mpc_icon__padding_divider="true" mpc_divider__disable="true" mpc_divider__width="60" mpc_divider__lines_color="#88d482" mpc_divider__lines_weight="8" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:8px;padding-bottom:10px;"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT
);