<?php
//About Banner
return array(
	'name'             => esc_html__( 'Bg Image with Right Description', 'ciyashop' ),
	'template_category'=> esc_html__( 'Action Box', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row full_width="stretch_row" pgscore_bg_type="row-background-dark" first_background_type="image" first_background_image="660" first_background_size="cover" second_background_type="image" second_background_image="660" second_background_size="cover" pgscore_enable_responsive_settings="true" el_id="1519717474777-28155b21-b187" css=".vc_custom_1524056112802{padding-top: 120px !important;padding-bottom: 120px !important;background-image: url(http://ciyashop.potenzaglobalsolutions.com/watch/wp-content/uploads/sites/5/2018/02/watch-bg1.jpg?id=660) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" element_css_md=".vc_custom_1524056112807{padding-top: 100px !important;padding-bottom: 100px !important;}" element_css_sm=".vc_custom_1524056112811{padding-top: 80px !important;padding-bottom: 80px !important;}" element_css_xs=".vc_custom_1524056112815{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column width="2/3" offset="vc_col-lg-offset-6 vc_col-lg-6 vc_col-md-offset-5 vc_col-md-7 vc_col-sm-offset-4"][vc_custom_heading text="Enjoy your life" font_container="tag:h2|font_size:3em|text_align:left|color:%23c49411|line_height:1em" use_theme_fonts="yes" font_weight="bold" text_transform="uppercase" letter_spacing="custom" css=".vc_custom_1524055810410{margin-bottom: 25px !important;}" letter_spacing_custom="3px"][vc_custom_heading text="Be Inspired by ciyashop. Connect with world watch store." font_container="tag:h4|text_align:left|line_height:1.3em" use_theme_fonts="yes" font_weight="400" css=".vc_custom_1524055789578{margin-bottom: 15px !important;}"][vc_column_text]Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.[/vc_column_text][mpc_button preset="preset_192" url="url:%23|||" font_color="#ffffff" font_size="18" font_line_height="1" font_transform="uppercase" font_align="center" title="Discover More" border_css="border-width:2px;border-color:#ffffff;border-style:solid;" padding_divider="true" padding_css="padding-top:18px;padding-right:30px;padding-bottom:18px;padding-left:30px;" margin_divider="true" margin_css="margin-top:5px;" hover_font_color="#c49411" hover_icon_color="#0a0404" hover_border_css="border-width:2px;border-color:#c49411;border-style:solid;"][/vc_column][/vc_row]
CONTENT
);