<?php
//About Banner
return array(
	'name'             => esc_html__( 'Action Box Image Color Overlay', 'ciyashop' ),
	'template_category'=> esc_html__( 'Action Box', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row full_width="stretch_row" pgscore_background_position="center-top" enable_first_overlay="true" first_overlay_opacity="80" first_background_color="#2985e1" enable_parallax="true" pgscore_enable_responsive_settings="true" el_id="1514971744862-9bd15f84-cb6d" css=".vc_custom_1524054826222{padding-top: 70px !important;padding-bottom: 60px !important;background-image: url(http://ciyashop.potenzaglobalsolutions.com/medical/wp-content/uploads/revslider/click-shop4/ed5be-01.jpg?id=11500) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" element_css_md=".vc_custom_1524054826227{padding-top: 60px !important;}" element_css_sm=".vc_custom_1524054826232{padding-top: 50px !important;padding-bottom: 50px !important;}" element_css_xs=".vc_custom_1524054826236{padding-top: 40px !important;padding-bottom: 40px !important;}"][vc_column css=".vc_custom_1514899656779{padding-top: 0px !important;}"][vc_custom_heading text="Free Appointment Booking" font_container="tag:h2|text_align:center|color:%23ffffff" use_theme_fonts="yes" font_weight="800" css=".vc_custom_1514965963570{margin-bottom: 20px !important;}"][vc_custom_heading text="Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, scrambled it to make a type specimen book." font_container="tag:h6|text_align:center|color:%23ffffff|line_height:34px" use_theme_fonts="yes" css=".vc_custom_1514966304979{margin-bottom: 20px !important;padding-right: 15% !important;padding-left: 15% !important;}"][vc_row_inner][vc_column_inner el_class="text-center" css=".vc_custom_1514968168217{padding-top: 0px !important;}"][mpc_button preset="mpc_preset_86" url="url:%23|||" font_color="#ffffff" font_size="14" font_transform="uppercase" title="Make an Appointment" border_css="border-width:2px;border-color:#ffffff;border-style:solid;border-radius:5px;" padding_divider="true" padding_css="padding-top:18px;padding-right:40px;padding-bottom:18px;padding-left:40px;" margin_divider="true" hover_font_color="#2985e1" hover_background_color="#ffffff" hover_background_effect="slide-right"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT
);