<?php
//About Banner
return array(
	'name'             => esc_html__( 'Action Box Bg Image', 'ciyashop' ),
	'template_category'=> esc_html__( 'Action Box', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row full_width="stretch_row" pgscore_bg_type="row-background-dark" pgscore_background_position="center-center" enable_first_overlay="true" first_overlay_opacity="40" first_background_color="#000000" enable_parallax="true" parallax_background="11040" parallax_style="classic-fast" pgscore_enable_responsive_settings="true" el_id="1519389276648-af4df3b3-9647" css=".vc_custom_1524053751896{padding-top: 100px !important;padding-bottom: 100px !important;}" element_css_md=".vc_custom_1524053751900{padding-top: 80px !important;padding-bottom: 80px !important;}" element_css_sm=".vc_custom_1524053751903{padding-top: 60px !important;padding-bottom: 60px !important;}" element_css_xs=".vc_custom_1524053751907{padding-top: 40px !important;padding-bottom: 40px !important;}"][vc_column css=".vc_custom_1519390106353{padding-top: 0px !important;}"][vc_row_inner css=".vc_custom_1519389915142{padding-right: 15px !important;padding-left: 15px !important;}"][vc_column_inner css=".vc_custom_1519389853789{border-top-width: 4px !important;border-right-width: 4px !important;border-bottom-width: 4px !important;border-left-width: 4px !important;padding-top: 40px !important;padding-right: 10% !important;padding-bottom: 40px !important;padding-left: 10% !important;border-left-color: #ffffff !important;border-left-style: solid !important;border-right-color: #ffffff !important;border-right-style: solid !important;border-top-color: #ffffff !important;border-top-style: solid !important;border-bottom-color: #ffffff !important;border-bottom-style: solid !important;}"][vc_custom_heading text="We offer Fashion Accessories at 50% discount" font_container="tag:h2|text_align:center" use_theme_fonts="yes" font_weight="600"][vc_custom_heading text="We sell not only top quality products, but give our customers a positive online shopping experience. Purchase the goods you need every day or just like in a few clicks or taps, depending on the device you use to access the Internet." font_container="tag:p|text_align:center" use_theme_fonts="yes" font_weight="400"][vc_btn title="Shop Now" style="flat" shape="square" color="white" align="center" link="url:%23|||" css=".vc_custom_1513146613758{margin-bottom: 0px !important;}"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT
);