<?php
//About Banner
return array(
	'name'             => esc_html__( 'Action Box with Dotted Border', 'ciyashop' ),
	'template_category'=> esc_html__( 'Action Box', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row pgscore_enable_responsive_settings="true" el_id="1515145585880-1e4b6b01-fb50" css=".vc_custom_1524054379711{margin-top: 80px !important;margin-bottom: 80px !important;}" element_css_sm=".vc_custom_1524054379718{margin-top: 50px !important;margin-bottom: 50px !important;}" element_css_xs=".vc_custom_1524054379721{margin-top: 40px !important;margin-bottom: 40px !important;}" element_css_md=".vc_custom_1524054379715{margin-top: 60px !important;margin-bottom: 60px !important;}"][vc_column][mpc_callout title_font_color="#2985e1" title_font_size="28" title_font_line_height="1.3" title_font_transform="none" title_font_align="left" title="Free Appointment Booking" title_margin_divider="true" title_margin_css="margin-top:0px;margin-bottom:10px;" content_width="100" content_font_color="#9c9c9c" content_font_size="17" content_font_line_height="1.3" content_font_align="left" content_margin_divider="true" content_margin_css="margin-top:0px;margin-bottom:0px;" icon="lnr lnr-calendar-full" icon_color="#2985e1" icon_size="60" icon_border_divider="true" icon_padding_divider="true" icon_margin_divider="true" icon_margin_css="margin-top:-5px;margin-right:10px;" border_divider="true" border_css="border-color:#dddddd;border-style:dashed;border-radius:10px;" padding_divider="true" padding_css="padding-top:30px;padding-right:40px;padding-bottom:30px;padding-left:40px;" margin_divider="true" mpc_button__url="url:http%3A%2F%2Fthemes.potenzaglobalsolutions.com%2Fciya-shop%2Fmedical%2Fappointment%2F|title:Link||" mpc_button__font_color="#f7f7f7" mpc_button__font_size="16" mpc_button__font_transform="uppercase" mpc_button__title="Make an Appointment" mpc_button__background_color="#2985e1" mpc_button__border_divider="true" mpc_button__border_css="border-top:2px;border-right:1px;border-bottom:2px;border-left:2px;border-color:#2985e1;border-style:solid;border-radius:3px;" mpc_button__padding_divider="true" mpc_button__padding_css="padding-top:12px;padding-right:30px;padding-bottom:12px;padding-left:30px;" mpc_button__margin_divider="true" mpc_button__margin_css="margin-left:0px;" mpc_button__hover_font_color="#2985e1" mpc_button__hover_background_color="#ffffff" mpc_button__hover_border_divider="true" mpc_button__hover_border_css="border-top:2px;border-right:1px;border-bottom:2px;border-left:2px;border-color:#2985e1;border-style:solid;border-radius:3px;" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__lines_color="#f7f7f7" mpc_divider__lines_weight="2" mpc_divider__padding_divider="true" mpc_divider__margin_divider="true" mpc_divider__margin_css="margin-bottom:-10px;" mpc_ribbon__border_divider="true" mpc_ribbon__padding_divider="true" mpc_ribbon__margin_divider="true"]Lorem Ipsum has been the industry's standard dummy.</p>
<p>[/mpc_callout][/vc_column][/vc_row]
CONTENT
);