<?php
//About Banner
return array(
	'name'             => esc_html__( 'Background Image With Video', 'ciyashop' ),
	'template_category'=> esc_html__( 'Video', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
<p>[vc_row full_width="stretch_row" equal_height="yes" content_placement="middle" pgscore_bg_type="row-background-dark" enable_first_overlay="true" first_overlay_opacity="20" first_background_color="#000000" pgscore_enable_responsive_settings="true" el_id="1533303990362-eff5b12b-ad15" css=".vc_custom_1533646459757{padding-top: 120px !important;padding-bottom: 90px !important;background-image: url(http://ciyashop.potenzaglobalsolutions.com/fashion-vintage/wp-content/uploads/sites/29/2018/08/history-bg.jpg?id=485) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" element_css_md=".vc_custom_1533646459759{padding-top: 90px !important;padding-bottom: 60px !important;}" element_css_sm=".vc_custom_1533646459759{padding-top: 70px !important;padding-bottom: 40px !important;}" element_css_xs=".vc_custom_1533646459761{padding-top: 50px !important;padding-bottom: 20px !important;}"][vc_column width="1/2" css=".vc_custom_1533794196159{margin-right: 15px !important;margin-bottom: 30px !important;margin-left: 15px !important;padding-top: 11em !important;padding-bottom: 11em !important;background-image: url(http://ciyashop.potenzaglobalsolutions.com/fashion-vintage/wp-content/uploads/sites/29/2018/08/video-bg.jpg?id=486) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="text-center"][mpc_lightbox preset="mpc_preset_3" lightbox_url="url:https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D0Rf87cXbfLk%26t%3D1s|||" mpc_button__font_color="#ffffff" mpc_button__font_size="14" mpc_button__font_line_height="1.6" mpc_button__font_transform="uppercase" mpc_button__font_align="center" mpc_button__title="See Video" mpc_button__icon="icnm icnm-play2" mpc_button__icon_color="#ffffff" mpc_button__icon_size="30" mpc_button__icon_effect="push_out-bottom" mpc_button__border_css="border-width:2px;border-color:#ffffff;border-style:solid;border-radius:0px;" mpc_button__padding_divider="true" mpc_button__padding_css="padding-top:13px;padding-right:34px;padding-bottom:13px;padding-left:34px;" mpc_button__hover_font_color="#ffffff" mpc_button__hover_background_effect="slide-left" mpc_button__hover_border_css="border-color:#ffffff;border-style:solid;border-radius:0px;"][/vc_column][vc_column width="1/2" el_class="text-center" css=".vc_custom_1533357346968{margin-bottom: 30px !important;padding-top: 0px !important;}"][vc_custom_heading text="History Of Leather Store" font_container="tag:h2|text_align:center" use_theme_fonts="yes"][vc_column_text]</p>
<p style="text-align: center;">Making a decision to do something – this is the first step. We all know that nothing moves until someone makes a decision. The first action is always in making the decision to proceed. This is a fundamental step, which most people overlook.</p>
<p>[/vc_column_text][mpc_button preset="preset_192" url="url:%23|||" font_color="#323232" font_size="12" font_line_height="1" font_transform="uppercase" font_align="inherit" title="Read More" background_color="#ffffff" border_css="border-width:0px;border-radius:0px;" padding_divider="true" padding_css="padding-top:18px;padding-right:34px;padding-bottom:18px;padding-left:34px;" margin_divider="true" hover_font_color="#ffffff" hover_background_color="#baa17d" hover_border_css="border-radius:0px;"][/vc_column][/vc_row]</p>
CONTENT
);