<?php
//About Banner
return array(
	'name'             => esc_html__( 'Contact Info left Map', 'ciyashop' ),
	'template_category'=> esc_html__( 'Contact Info', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row equal_height="yes" content_placement="middle" pgscore_enable_responsive_settings="true" el_id="1522841153209-4b18b3ab-f1f0" css=".vc_custom_1523256180402{margin-top: 100px !important;margin-bottom: 60px !important;}" element_css_md=".vc_custom_1523256180406{margin-top: 80px !important;margin-bottom: 40px !important;}" element_css_sm=".vc_custom_1523256180409{margin-top: 60px !important;margin-bottom: 20px !important;}" element_css_xs=".vc_custom_1523256180412{margin-top: 40px !important;margin-bottom: 0px !important;}"][vc_column width="1/2" css=".vc_custom_1522841517137{margin-bottom: 40px !important;}"][vc_gmaps link="#E-8_JTNDaWZyYW1lJTIwc3JjJTNEJTIyaHR0cHMlM0ElMkYlMkZ3d3cuZ29vZ2xlLmNvbSUyRm1hcHMlMkZlbWJlZCUzRnBiJTNEJTIxMW0xOCUyMTFtMTIlMjExbTMlMjExZDYzMDQuODI5OTg2MTMxMjcxJTIxMmQtMTIyLjQ3NDY5NjgwMzMwOTIlMjEzZDM3LjgwMzc0NzUyMTYwNDQzJTIxMm0zJTIxMWYwJTIxMmYwJTIxM2YwJTIxM20yJTIxMWkxMDI0JTIxMmk3NjglMjE0ZjEzLjElMjEzbTMlMjExbTIlMjExczB4ODA4NTg2ZTYzMDI2MTVhMSUyNTNBMHg4NmJkMTMwMjUxNzU3YzAwJTIxMnNTdG9yZXklMkJBdmUlMjUyQyUyQlNhbiUyQkZyYW5jaXNjbyUyNTJDJTJCQ0ElMkI5NDEyOSUyMTVlMCUyMTNtMiUyMTFzZW4lMjEyc3VzJTIxNHYxNDM1ODI2NDMyMDUxJTIyJTIwd2lkdGglM0QlMjI2MDAlMjIlMjBoZWlnaHQlM0QlMjI0NTAlMjIlMjBmcmFtZWJvcmRlciUzRCUyMjAlMjIlMjBzdHlsZSUzRCUyMmJvcmRlciUzQTAlMjIlMjBhbGxvd2Z1bGxzY3JlZW4lM0UlM0MlMkZpZnJhbWUlM0U=" css=".vc_custom_1522930671777{margin-bottom: 0px !important;border-radius: 20px !important;}" el_class="overflow-h"][/vc_column][vc_column width="1/2" css=".vc_custom_1522841508089{margin-bottom: 40px !important;}"][vc_custom_heading text="Let's Get In Touch!<br />
" google_fonts="font_family:Fredoka%20One%3Aregular|font_style:400%20regular%3A400%3Anormal" css=".vc_custom_1524206695209{margin-bottom: 30px !important;}"][vc_column_text]It would be great to hear from you! If you got any questions, please do not hesitate to send us a message. We are looking forward to hearing from you! We reply within 24 hours!<br />
[/vc_column_text][mpc_icon_column layout="style_3" alignment="left" border_divider="true" padding_divider="true" margin_divider="true" margin_css="margin-bottom:15px;" title_margin_divider="true" content_font_size="14" content_font_line_height="2" content_font_align="left" content_margin_divider="true" hover_border_divider="true" mpc_icon__icon="ti ti-email" mpc_icon__icon_color="#00a4d3" mpc_icon__icon_size="26" mpc_icon__border_divider="true" mpc_icon__padding_divider="true" mpc_icon__margin_divider="true" mpc_icon__hover_border_divider="true" mpc_divider__disable="true" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__padding_divider="true" mpc_divider__margin_divider="true"]support@ciyashop.com<br />
[/mpc_icon_column][mpc_icon_column layout="style_3" alignment="left" border_divider="true" padding_divider="true" margin_divider="true" margin_css="margin-bottom:15px;" title_margin_divider="true" content_font_size="14" content_font_line_height="2" content_font_align="left" content_margin_divider="true" hover_border_divider="true" mpc_icon__icon="fa fa-phone" mpc_icon__icon_color="#00a4d3" mpc_icon__icon_size="26" mpc_icon__border_divider="true" mpc_icon__padding_divider="true" mpc_icon__margin_divider="true" mpc_icon__hover_border_divider="true" mpc_divider__disable="true" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__padding_divider="true" mpc_divider__margin_divider="true"]126-632-2345<br />
[/mpc_icon_column][mpc_icon_column layout="style_3" alignment="left" border_divider="true" padding_divider="true" padding_css="padding-bottom:15px;" margin_divider="true" title_margin_divider="true" content_font_size="14" content_font_line_height="2" content_font_align="left" content_margin_divider="true" hover_border_divider="true" mpc_icon__icon="ti ti-location-pin" mpc_icon__icon_color="#00a4d3" mpc_icon__icon_size="26" mpc_icon__border_divider="true" mpc_icon__padding_divider="true" mpc_icon__margin_divider="true" mpc_icon__hover_border_divider="true" mpc_divider__disable="true" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__padding_divider="true" mpc_divider__margin_divider="true"]Porterfield 508 Virginia Street Chicago, Opp M.<br />
Alexander Building. IL 60653<br />
[/mpc_icon_column][pgscore_social_icons style="flat-color" shape="rounded" size="small" list_items="%5B%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-facebook%22%7D%2C%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-twitter%22%7D%2C%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-google-plus%22%7D%2C%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-linkedin%22%7D%2C%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-pinterest%22%7D%5D" element_css=".vc_custom_1522929594637{margin-top: 20px !important;margin-left: 45px !important;}"][/vc_column][/vc_row]
CONTENT
);