<?php
//About Banner
return array(
	'name'             => esc_html__( 'full widht 3 box', 'ciyashop' ),
	'template_category'=> esc_html__( 'Contact Info', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row full_width="stretch_row_content_no_spaces" el_id="1518691276580-28860932-9054"][vc_column offset="vc_col-lg-4 vc_col-md-4" css=".vc_custom_1524203072390{padding-top: 0px !important;}"][mpc_icon_column background_color="#f1dc00" border_divider="true" padding_divider="true" padding_css="padding-top:4em;padding-right:1em;padding-bottom:4em;padding-left:1em;" margin_divider="true" title_font_preset="mpc_preset_39" title_font_color="#323232" title_font_size="24" title="Our Location" title_margin_divider="true" title_margin_css="margin-bottom:10px;" content_font_color="#323232" content_margin_divider="true" hover_border_divider="true" mpc_icon__icon="etl etl-map-pin" mpc_icon__icon_color="#323232" mpc_icon__icon_size="50" mpc_icon__border_divider="true" mpc_icon__padding_divider="true" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-bottom:20px;" mpc_icon__hover_border_divider="true" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__padding_divider="true" mpc_divider__margin_divider="true"]1635 Franklin Street Montgomery,
Near Sherwood Mall. AL 36104[/mpc_icon_column][/vc_column][vc_column offset="vc_col-lg-4 vc_col-md-4" css=".vc_custom_1524203079796{padding-top: 0px !important;}"][mpc_icon_column background_color="#e0cd03" border_divider="true" padding_divider="true" padding_css="padding-top:4em;padding-right:1em;padding-bottom:4em;padding-left:1em;" margin_divider="true" title_font_preset="mpc_preset_39" title_font_color="#323232" title_font_size="24" title="Call Us" title_margin_divider="true" title_margin_css="margin-bottom:10px;" content_font_color="#323232" content_margin_divider="true" hover_border_divider="true" mpc_icon__icon="etl etl-phone" mpc_icon__icon_color="#323232" mpc_icon__icon_size="50" mpc_icon__border_divider="true" mpc_icon__padding_divider="true" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-bottom:20px;" mpc_icon__hover_border_divider="true" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__padding_divider="true" mpc_divider__margin_divider="true"]126-632-2345
857-778-1265[/mpc_icon_column][/vc_column][vc_column offset="vc_col-lg-4 vc_col-md-4" css=".vc_custom_1524203088095{padding-top: 0px !important;}"][mpc_icon_column background_color="#d6c402" border_divider="true" padding_divider="true" padding_css="padding-top:4em;padding-right:1em;padding-bottom:4em;padding-left:1em;" margin_divider="true" title_font_preset="mpc_preset_39" title_font_color="#323232" title_font_size="24" title="Connect Online" title_margin_divider="true" title_margin_css="margin-bottom:10px;" content_font_color="#323232" content_margin_divider="true" hover_border_divider="true" mpc_icon__icon="etl etl-desktop" mpc_icon__icon_color="#323232" mpc_icon__icon_size="50" mpc_icon__border_divider="true" mpc_icon__padding_divider="true" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-bottom:20px;" mpc_icon__hover_border_divider="true" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__padding_divider="true" mpc_divider__margin_divider="true"]support@ciyashop.com
gethelp@ciyashop.com[/mpc_icon_column][/vc_column][/vc_row]
CONTENT
);