<?php
//About Banner
return array(
	'name'             => esc_html__( 'Contact Info 3 Box', 'ciyashop' ),
	'template_category'=> esc_html__( 'Contact Info', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row pgscore_enable_responsive_settings="true" el_id="1517578456227-29bbaeb3-545d" css=".vc_custom_1517817973842{margin-top: 80px !important;margin-bottom: 50px !important;}" element_css_md=".vc_custom_1517817973844{margin-top: 60px !important;margin-bottom: 30px !important;}" element_css_sm=".vc_custom_1517817973846{margin-top: 50px !important;margin-bottom: 20px !important;}" element_css_xs=".vc_custom_1517817973848{margin-top: 40px !important;margin-bottom: 10px !important;}"][vc_column][vc_row_inner][vc_column_inner offset="vc_col-lg-6 vc_col-md-8"][vc_custom_heading text="Let's Get In Touch!<br />
" use_theme_fonts="yes" font_weight="700" css=".vc_custom_1523447524273{margin-bottom: 25px !important;}"][vc_custom_heading text="It would be great to hear from you! If you got any questions, please do not hesitate to send us a message." font_container="tag:p|text_align:left" use_theme_fonts="yes" css=".vc_custom_1523447534657{margin-bottom: 35px !important;}"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner css=".vc_custom_1517818064129{margin-bottom: 30px !important;}" offset="vc_col-lg-4 vc_col-md-4"][mpc_icon_column preset="mpc_preset_16" alignment="left" border_css="border-radius:20px;" padding_css="padding:0px;" title_font_preset="mpc_preset_17" title_font_color="#444444" title_font_size="17" title_font_line_height="1.4" title_font_transform="uppercase" title_font_align="left" title="Address" title_margin_divider="true" title_margin_css="margin-bottom:8px;" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" content_font_align="left" mpc_icon__transition="slide-right" mpc_icon__icon="etl etl-map-pin" mpc_icon__icon_color="#f53d03" mpc_icon__icon_size="40" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-top:0px;margin-right:0px;margin-bottom:20px;margin-left:0px;" mpc_icon__hover_border_css="border-color:#f3f3f3;" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__align="left" mpc_divider__content_padding_divider="true" mpc_divider__content_padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_divider__lines_color="#dddddd" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:3px;padding-bottom:3px;"]1635 Franklin Street Montgomery,<br />
Near Sherwood Mall. AL 36104<br />
[/mpc_icon_column][/vc_column_inner][vc_column_inner css=".vc_custom_1517818072746{margin-bottom: 30px !important;}" offset="vc_col-lg-4 vc_col-md-4"][mpc_icon_column preset="mpc_preset_16" alignment="left" border_css="border-radius:20px;" padding_css="padding:0px;" title_font_preset="mpc_preset_17" title_font_color="#444444" title_font_size="17" title_font_line_height="1.4" title_font_transform="uppercase" title_font_align="left" title="Contact" title_margin_divider="true" title_margin_css="margin-bottom:8px;" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" content_font_align="left" mpc_icon__transition="slide-right" mpc_icon__icon="etl etl-phone" mpc_icon__icon_color="#f53d03" mpc_icon__icon_size="40" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-top:0px;margin-right:0px;margin-bottom:20px;margin-left:0px;" mpc_icon__hover_border_css="border-color:#f3f3f3;" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__align="left" mpc_divider__content_padding_divider="true" mpc_divider__content_padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_divider__lines_color="#dddddd" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:3px;padding-bottom:3px;"]<a href="#">126-632-2345</a><br />Mon to Fri 09:00 am - 6:30 pm[/mpc_icon_column][/vc_column_inner][vc_column_inner css=".vc_custom_1517818080822{margin-bottom: 30px !important;}" offset="vc_col-lg-4 vc_col-md-4"][mpc_icon_column preset="mpc_preset_16" alignment="left" border_css="border-radius:20px;" padding_css="padding:0px;" title_font_preset="mpc_preset_17" title_font_color="#444444" title_font_size="17" title_font_line_height="1.4" title_font_transform="uppercase" title_font_align="left" title="Support" title_margin_divider="true" title_margin_css="margin-bottom:8px;" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" content_font_align="left" mpc_icon__transition="slide-right" mpc_icon__icon="etl etl-envelope" mpc_icon__icon_color="#f53d03" mpc_icon__icon_size="40" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-top:0px;margin-right:0px;margin-bottom:20px;margin-left:0px;" mpc_icon__hover_border_css="border-color:#f3f3f3;" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__align="left" mpc_divider__content_padding_divider="true" mpc_divider__content_padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_divider__lines_color="#dddddd" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:3px;padding-bottom:3px;"]<a href="#">support@ciyashop.com</a><br />24 x 7 Online Support[/mpc_icon_column][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT
);