<?php
//About Banner
return array(
	'name'             => esc_html__( 'Counter Top Icon Rounded', 'ciyashop' ),
	'template_category'=> esc_html__( 'Counter', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
<p>[vc_row full_width="stretch_row" pgscore_bg_type="row-background-dark" enable_first_overlay="true" first_overlay_opacity="80" first_background_color="#000000" pgscore_enable_responsive_settings="true" el_id="1523971202020-163178ac-a786" css=".vc_custom_1524055477630{padding-top: 80px !important;padding-bottom: 50px !important;background-image: url(http://ciyashop.potenzaglobalsolutions.com/petstore/wp-content/uploads/sites/17/2018/04/counter-bg.jpg?id=534) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" element_css_md=".vc_custom_1524055477632{padding-top: 60px !important;padding-bottom: 30px !important;}" element_css_sm=".vc_custom_1524055477633{padding-top: 50px !important;padding-bottom: 20px !important;}" element_css_xs=".vc_custom_1524055477634{padding-top: 40px !important;padding-bottom: 10px !important;}"][vc_column css=".vc_custom_1523972514975{padding-top: 0px !important;}"][vc_row_inner][vc_column_inner offset="vc_col-lg-offset-2 vc_col-lg-8"][vc_custom_heading text="Some Interesting Facts" font_container="tag:h2|text_align:center" use_theme_fonts="yes"][vc_column_text css=".vc_custom_1523973002173{margin-bottom: 40px !important;}"]</p>
<p style="text-align: center;">No one rejects dislikes or avoids pleasure itself because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.</p>
<p>[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner el_class="text-center" width="1/4" offset="vc_col-xs-6"][mpc_counter preset="mpc_preset_14" title_font_color="#ffffff" title_font_size="18" title_font_line_height="1" title_font_transform="none" title="Veterinary" counter_font_color="#ffffff" counter_font_size="40" counter_font_line_height="1.5" type="random" value="380" duration="2000" delay="0" margin_divider="true" margin_css="margin-bottom:30px;" mpc_icon__icon="fa fa-paw" mpc_icon__icon_color="#ffffff" mpc_icon__icon_size="40" mpc_icon__background_color="rgba(255,255,255,0.14)" mpc_icon__border_css="border-radius:500px;" mpc_icon__padding_css="padding:26px;" mpc_icon__margin_divider="true" mpc_divider__disable="true"][/vc_column_inner][vc_column_inner el_class="text-center" width="1/4" offset="vc_col-xs-6"][mpc_counter preset="mpc_preset_14" title_font_color="#ffffff" title_font_size="18" title_font_line_height="1" title_font_transform="none" title="Pet Adoption" counter_font_color="#ffffff" counter_font_size="40" counter_font_line_height="1.5" type="random" value="275" duration="2000" delay="0" margin_divider="true" margin_css="margin-bottom:30px;" mpc_icon__icon="mi mi-group" mpc_icon__icon_color="#ffffff" mpc_icon__icon_size="40" mpc_icon__background_color="rgba(255,255,255,0.14)" mpc_icon__border_css="border-radius:500px;" mpc_icon__padding_css="padding:26px;" mpc_icon__margin_divider="true" mpc_divider__disable="true"][/vc_column_inner][vc_column_inner el_class="text-center" width="1/4" offset="vc_col-xs-6"][mpc_counter preset="mpc_preset_14" title_font_color="#ffffff" title_font_size="18" title_font_line_height="1" title_font_transform="none" title="Dog Walking" counter_font_color="#ffffff" counter_font_size="40" counter_font_line_height="1.5" type="random" value="595" duration="2000" delay="0" margin_divider="true" margin_css="margin-bottom:30px;" mpc_icon__icon="mi mi-directions_walk" mpc_icon__icon_color="#ffffff" mpc_icon__icon_size="40" mpc_icon__background_color="rgba(255,255,255,0.14)" mpc_icon__border_css="border-radius:500px;" mpc_icon__padding_css="padding:26px;" mpc_icon__margin_divider="true" mpc_divider__disable="true"][/vc_column_inner][vc_column_inner el_class="text-center" width="1/4" offset="vc_col-xs-6"][mpc_counter preset="mpc_preset_14" title_font_color="#ffffff" title_font_size="18" title_font_line_height="1" title_font_transform="none" title="Pet Grooming" counter_font_color="#ffffff" counter_font_size="40" counter_font_line_height="1.5" type="random" value="260" duration="2000" delay="0" margin_divider="true" margin_css="margin-bottom:30px;" mpc_icon__icon="mi mi-content_cut" mpc_icon__icon_color="#ffffff" mpc_icon__icon_size="40" mpc_icon__background_color="rgba(255,255,255,0.14)" mpc_icon__border_css="border-radius:500px;" mpc_icon__padding_css="padding:26px;" mpc_icon__margin_divider="true" mpc_divider__disable="true"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]</p>

CONTENT
);