<?php
//About Banner
return array(
	'name'             => esc_html__( 'Customer Reviews', 'ciyashop' ),
	'template_category'=> esc_html__( 'Testimonial', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
<p>[vc_row pgscore_enable_responsive_settings="true" el_id="1531384189414-4cc2d525-25dd" css=".vc_custom_1534159185037{padding-top: 80px !important;padding-bottom: 80px !important;}" element_css_md=".vc_custom_1534159185039{padding-top: 60px !important;padding-bottom: 60px !important;}" element_css_sm=".vc_custom_1534159185041{padding-top: 50px !important;padding-bottom: 50px !important;}" element_css_xs=".vc_custom_1534159185041{padding-top: 40px !important;padding-bottom: 40px !important;}"][vc_column offset="vc_col-lg-offset-1 vc_col-lg-10 vc_col-md-offset-1 vc_col-md-10"][vc_custom_heading text="Customer Reviews" font_container="tag:h2|text_align:center" use_theme_fonts="yes" css=".vc_custom_1531467769188{margin-bottom: 30px !important;padding-top: 0px !important;}"][mpc_carousel_testimonial loop="true" rows="1" cols="1" gap="0" start_at="1" min_height="0" mpc_navigation__preset="mpc_preset_10"][mpc_testimonial preset="mpc_preset_2" layout="style_4" background_color="#f6f4f5" url="url:%23||target:%20_blank|" testimonial_font_color="#969696" testimonial_font_size="24" testimonial_font_line_height="1.4" testimonial_font_align="center" border_divider="true" padding_divider="true" padding_css="padding-top:4em;padding-right:4em;padding-bottom:1.6em;padding-left:4em;" margin_divider="true" margin_css="margin-right:-15px;margin-bottom:0px;margin-left:-15px;"]</p>
<p style="text-align: center;">Excellent Customer support! These guys reply within minutes sometimes and really help you with when you need them. The theme itself is very extended as well. Happy with my purchase!</p>
<p>[/mpc_testimonial][mpc_testimonial preset="mpc_preset_2" layout="style_4" background_color="#f6f4f5" url="url:%23||target:%20_blank|" testimonial_font_color="#969696" testimonial_font_size="24" testimonial_font_line_height="1.4" testimonial_font_align="center" border_divider="true" padding_divider="true" padding_css="padding-top:4em;padding-right:4em;padding-bottom:1.6em;padding-left:4em;" margin_divider="true" margin_css="margin-right:-15px;margin-bottom:0px;margin-left:-15px;"]</p>
<p style="text-align: center;">Excellent Customer support! These guys reply within minutes sometimes and really help you with when you need them. The theme itself is very extended as well. Happy with my purchase!</p>
<p>[/mpc_testimonial][mpc_testimonial preset="mpc_preset_2" layout="style_4" background_color="#f6f4f5" url="url:%23||target:%20_blank|" testimonial_font_color="#969696" testimonial_font_size="24" testimonial_font_line_height="1.4" testimonial_font_align="center" border_divider="true" padding_divider="true" padding_css="padding-top:4em;padding-right:4em;padding-bottom:1.6em;padding-left:4em;" margin_divider="true" margin_css="margin-right:-15px;margin-bottom:0px;margin-left:-15px;"]</p>
<p style="text-align: center;">Excellent Customer support! These guys reply within minutes sometimes and really help you with when you need them. The theme itself is very extended as well. Happy with my purchase!</p>
<p>[/mpc_testimonial][mpc_testimonial preset="mpc_preset_2" layout="style_4" background_color="#f6f4f5" url="url:%23||target:%20_blank|" testimonial_font_color="#969696" testimonial_font_size="24" testimonial_font_line_height="1.4" testimonial_font_align="center" border_divider="true" padding_divider="true" padding_css="padding-top:4em;padding-right:4em;padding-bottom:1.6em;padding-left:4em;" margin_divider="true" margin_css="margin-right:-15px;margin-bottom:0px;margin-left:-15px;"]</p>
<p style="text-align: center;">Excellent Customer support! These guys reply within minutes sometimes and really help you with when you need them. The theme itself is very extended as well. Happy with my purchase!</p>
<p>[/mpc_testimonial][mpc_testimonial preset="mpc_preset_2" layout="style_4" background_color="#f6f4f5" url="url:%23||target:%20_blank|" testimonial_font_color="#969696" testimonial_font_size="24" testimonial_font_line_height="1.4" testimonial_font_align="center" border_divider="true" padding_divider="true" padding_css="padding-top:4em;padding-right:4em;padding-bottom:1.6em;padding-left:4em;" margin_divider="true" margin_css="margin-right:-15px;margin-bottom:0px;margin-left:-15px;"]</p>
<p style="text-align: center;">Excellent Customer support! These guys reply within minutes sometimes and really help you with when you need them. The theme itself is very extended as well. Happy with my purchase!</p>
<p>[/mpc_testimonial][/mpc_carousel_testimonial][/vc_column][/vc_row]</p>
CONTENT
);