<?php
//About Banner
return array(
	'name'             => esc_html__( 'Right Contact Info', 'ciyashop' ),
	'template_category'=> esc_html__( 'Form', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row pgscore_enable_responsive_settings="true" el_id="1521792064473-766dff23-4c35" css=".vc_custom_1525335543265{margin-top: 80px !important;}" element_css_md=".vc_custom_1525335543271{margin-top: 60px !important;}" element_css_sm=".vc_custom_1525335543284{margin-top: 50px !important;}" element_css_xs=".vc_custom_1525335543289{margin-top: 40px !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-6"][vc_custom_heading text="Contact Information :" font_container="tag:h3|text_align:left" google_fonts="font_family:Patua%20One%3Aregular|font_style:400%20regular%3A400%3Anormal" css=".vc_custom_1525335632656{margin-bottom: 15px !important;}"][vc_column_text css=".vc_custom_1521792536332{margin-bottom: 0px !important;}"]Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.

[/vc_column_text][/vc_column][/vc_row][vc_row el_id="1521782109117-2d1336f9-3baa" css=".vc_custom_1525335569502{margin-bottom: 60px !important;}" el_class="d-lg-flex"][vc_column offset="vc_col-lg-5 vc_col-md-6" css=".vc_custom_1521792962398{margin-top: 30px !important;}" el_class="order-lg-2"][vc_single_image source="external_link" css=".vc_custom_1525335460504{margin-bottom: 30px !important;}" custom_src="http://ciyashop.potenzaglobalsolutions.com/onveggie/wp-content/uploads/sites/10/2018/03/contact-img.jpg"][vc_custom_heading text="Contact Us" font_container="tag:h5|text_align:left" google_fonts="font_family:Patua%20One%3Aregular|font_style:400%20regular%3A400%3Anormal" css=".vc_custom_1525335650411{margin-bottom: 25px !important;}"][mpc_icon_column layout="style_3" alignment="left" border_divider="true" padding_divider="true" margin_divider="true" margin_css="margin-bottom:15px;" title_font_color="#444444" title_font_size="17" title_font_line_height="1.4" title_font_transform="uppercase" title_font_align="left" title_margin_divider="true" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" content_margin_divider="true" hover_border_divider="true" mpc_icon__icon="ti ti-location-pin" mpc_icon__icon_color="#1ab293" mpc_icon__icon_size="20" mpc_icon__border_divider="true" mpc_icon__border_css="border-radius:0px;" mpc_icon__padding_divider="true" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-right:15px;" mpc_icon__hover_border_divider="true" mpc_icon__hover_border_css="border-radius:20px;" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__align="left" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__content_padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_divider__lines_color="#dddddd" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:3px;padding-bottom:3px;" mpc_divider__margin_divider="true"]1635 Franklin Street Montgomery,
Near Sherwood Mall. AL 36104
[/mpc_icon_column][mpc_icon_column preset="mpc_preset_10" layout="style_3" alignment="left" padding_css="padding:0px;" margin_divider="true" margin_css="margin-bottom:15px;" title_font_color="#444444" title_font_size="17" title_font_line_height="1.4" title_font_transform="uppercase" title_font_align="left" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" mpc_icon__icon="ti ti-headphone-alt" mpc_icon__icon_color="#1ab293" mpc_icon__icon_size="20" mpc_icon__border_css="border-radius:0px;" mpc_icon__padding_divider="true" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-right:15px;" mpc_icon__hover_border_css="border-radius:20px;" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__align="left" mpc_divider__content_padding_divider="true" mpc_divider__content_padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_divider__lines_color="#dddddd" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:3px;padding-bottom:3px;"]126-632-2345
[/mpc_icon_column][mpc_icon_column preset="mpc_preset_10" layout="style_3" alignment="left" padding_css="padding:0px;" margin_divider="true" margin_css="margin-bottom:15px;" title_font_color="#444444" title_font_size="17" title_font_line_height="1.4" title_font_transform="uppercase" title_font_align="left" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" mpc_icon__icon="ti ti-email" mpc_icon__icon_color="#1ab293" mpc_icon__icon_size="20" mpc_icon__border_css="border-radius:0px;" mpc_icon__padding_divider="true" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-top:-6px;margin-right:15px;" mpc_icon__hover_border_css="border-radius:20px;" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__align="left" mpc_divider__content_padding_divider="true" mpc_divider__content_padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_divider__lines_color="#dddddd" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:3px;padding-bottom:3px;"]support@ciyashop.com
[/mpc_icon_column][pgscore_social_icons style="flat-color" shape="rounded" size="small" hover_style="color-hover" list_items="%5B%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-facebook%22%7D%2C%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-twitter%22%7D%2C%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-linkedin%22%7D%2C%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-instagram%22%7D%2C%7B%22link%22%3A%22url%3A%2523%7C%7C%7C%22%2C%22icon%22%3A%22fa%20fa-dribbble%22%7D%5D" element_css=".vc_custom_1521790111482{margin-top: 25px !important;}"][/vc_column][vc_column offset="vc_col-lg-7 vc_col-md-6" css=".vc_custom_1521792986358{margin-top: 30px !important;}" el_class="order-lg-1"][contact-form-7 id="9552"][/vc_column][/vc_row]
CONTENT
);