<?php
//About Banner
return array(
	'name'             => esc_html__( 'Form With Contact Info', 'ciyashop' ),
	'template_category'=> esc_html__( 'Form', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
<p>[vc_row pgscore_enable_responsive_settings="true" el_id="1523882268718-905d6973-fa1f" css=".vc_custom_1524287232668{padding-top: 60px !important;padding-bottom: 100px !important;}" element_css_md=".vc_custom_1524287232672{padding-top: 60px !important;padding-bottom: 110px !important;}" element_css_sm=".vc_custom_1524287232673{padding-top: 50px !important;padding-bottom: 50px !important;}" element_css_xs=".vc_custom_1524287232675{padding-top: 40px !important;padding-bottom: 40px !important;}"][vc_column css=".vc_custom_1524285742985{margin-bottom: 0px !important;}" offset="vc_col-lg-offset-2 vc_col-lg-8 vc_col-md-offset-1 vc_col-md-10"][vc_custom_heading text="Let’s get in touch!" font_container="tag:h3|text_align:center" use_theme_fonts="yes"][vc_column_text css=".vc_custom_1524285534597{margin-bottom: 0px !important;}"]</p>
<p style="text-align: center;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's when an unknown printer took.</p>
<p>[/vc_column_text][/vc_column][/vc_row][vc_row pgscore_enable_responsive_settings="true" el_id="1523883218538-4eaae810-3b06" css=".vc_custom_1534147058965{margin-right: 0px !important;margin-left: 0px !important;padding-bottom: 30px !important;}" element_css_md=".vc_custom_1534147058967{padding-bottom: 30px !important;}" element_css_sm=".vc_custom_1534147058968{padding-bottom: 20px !important;}" element_css_xs=".vc_custom_1534147058969{padding-bottom: 10px !important;}"][vc_column css=".vc_custom_1534147035382{margin-bottom: 30px !important;padding-top: 80px !important;padding-right: 150px !important;padding-bottom: 40px !important;padding-left: 50px !important;background-image: url(http://ciyashop.potenzaglobalsolutions.com/antique/wp-content/uploads/sites/16/2018/04/15.jpg?id=670) !important;}" el_class="antique-address-block" offset="vc_col-lg-6 vc_col-md-6"][vc_custom_heading text="Location" font_container="tag:h2|text_align:left|color:%23ffffff" use_theme_fonts="yes"][vc_column_text]</p>
<p style="color: #ffffff;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy.</p>
<p>[/vc_column_text][mpc_icon_column layout="style_3" alignment="left" border_divider="true" padding_divider="true" margin_divider="true" margin_css="margin-bottom:40px;" title_font_color="#ffffff" title_font_size="24" title_font_line_height="1" title_font_transform="none" title="Address" title_margin_divider="true" title_margin_css="margin-bottom:10px;" content_font_color="#ffffff" content_margin_divider="true" hover_border_divider="true" mpc_icon__icon="fa fa-home" mpc_icon__icon_color="#ffffff" mpc_icon__icon_size="26" mpc_icon__background_color="#7b5325" mpc_icon__border_css="border-radius:50px;" mpc_icon__padding_css="padding:10px;" mpc_icon__margin_divider="true" mpc_icon__hover_border_divider="true" mpc_divider__disable="true" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__padding_divider="true" mpc_divider__margin_divider="true"]1635 Franklin Street Montgomery, Near Sherwood Mall. AL 36104</p>
<p>[/mpc_icon_column][mpc_icon_column layout="style_3" alignment="left" border_divider="true" padding_divider="true" margin_divider="true" margin_css="margin-bottom:40px;" title_font_color="#ffffff" title_font_size="24" title_font_line_height="1" title_font_transform="none" title="Phone" title_margin_divider="true" title_margin_css="margin-bottom:10px;" content_font_color="#ffffff" content_margin_divider="true" hover_border_divider="true" mpc_icon__icon="fa fa-phone" mpc_icon__icon_color="#ffffff" mpc_icon__icon_size="26" mpc_icon__background_color="#7b5325" mpc_icon__border_divider="true" mpc_icon__border_css="border-radius:50px;" mpc_icon__padding_divider="true" mpc_icon__padding_css="padding:10px;" mpc_icon__margin_divider="true" mpc_icon__hover_border_divider="true" mpc_divider__disable="true" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__padding_divider="true" mpc_divider__margin_divider="true"]126-632-2345<br />
857-778-1265[/mpc_icon_column][mpc_icon_column layout="style_3" alignment="left" border_divider="true" padding_divider="true" margin_divider="true" margin_css="margin-bottom:40px;" title_font_color="#ffffff" title_font_size="24" title_font_line_height="1" title_font_transform="none" title="Email" title_margin_divider="true" title_margin_css="margin-bottom:10px;" content_font_color="#ffffff" content_margin_divider="true" hover_border_divider="true" mpc_icon__icon="fa fa-envelope-o" mpc_icon__icon_color="#ffffff" mpc_icon__icon_size="26" mpc_icon__background_color="#7b5325" mpc_icon__border_divider="true" mpc_icon__border_css="border-radius:50px;" mpc_icon__padding_css="padding:10px;" mpc_icon__margin_divider="true" mpc_icon__hover_border_divider="true" mpc_divider__disable="true" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__padding_divider="true" mpc_divider__margin_divider="true"]support@ciyashop.com<br />
gethelp@ciyashop.com</p>
<p>[/mpc_icon_column][/vc_column][vc_column css=".vc_custom_1534147040548{margin-top: -60px !important;margin-bottom: 30px !important;padding-top: 0px !important;background-color: #f5f5f5 !important;}" el_class="antique-contact-form" offset="vc_col-lg-6 vc_col-md-6"][vc_row_inner][vc_column_inner css=".vc_custom_1523953115557{margin-left: -60px !important;padding-top: 95px !important;padding-bottom: 95px !important;padding-left: 70px !important;background-color: #f5f5f5 !important;}"][contact-form-7 id="671"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]</p>
CONTENT
);