<?php
//About Banner
return array(
	'name'             => esc_html__( 'Rounded Icon in Dark BG', 'ciyashop' ),
	'template_category'=> esc_html__( 'Info Box', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row full_width="stretch_row" pgscore_enable_responsive_settings="true" el_id="1517402603834-af51aa29-08b1" css=".vc_custom_1524822722131{padding-top: 60px !important;padding-bottom: 30px !important;}" element_css_md=".vc_custom_1524822722135{padding-top: 60px !important;padding-bottom: 30px !important;}" element_css_sm=".vc_custom_1524822722139{padding-top: 50px !important;padding-bottom: 20px !important;}" element_css_xs=".vc_custom_1524822722142{padding-top: 40px !important;padding-bottom: 10px !important;}"][vc_column width="1/3" css=".vc_custom_1517826724646{margin-bottom: 30px !important;}"][mpc_icon_column layout="style_3" alignment="left" border_divider="true" padding_divider="true" margin_divider="true" title_font_color="#444444" title_font_size="18" title_font_line_height="1.4" title_font_transform="uppercase" title_font_align="left" title="Free Shipping" title_margin_divider="true" title_margin_css="margin-bottom:5px;" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" content_font_align="left" content_margin_divider="true" hover_border_divider="true" mpc_icon__icon="ti ti-truck" mpc_icon__icon_color="#ffffff" mpc_icon__icon_size="36" mpc_icon__background_color="#323232" mpc_icon__border_divider="true" mpc_icon__border_css="border-radius:60px;" mpc_icon__padding_css="padding:15px;" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-right:20px;" mpc_icon__hover_background_color="#f53d03" mpc_icon__hover_border_divider="true" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__align="left" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__content_padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_divider__lines_color="#dddddd" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:3px;padding-bottom:3px;" mpc_divider__margin_divider="true"]Free shipping on all Local Area order above $200</p>
<p>[/mpc_icon_column][/vc_column][vc_column width="1/3" css=".vc_custom_1517826731392{margin-bottom: 30px !important;}"][mpc_icon_column layout="style_3" alignment="left" border_divider="true" padding_divider="true" padding_css="padding:0px;" margin_divider="true" title_font_color="#444444" title_font_size="18" title_font_line_height="1.4" title_font_transform="uppercase" title_font_align="left" title="24/7 Support" title_margin_divider="true" title_margin_css="margin-bottom:5px;" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" content_font_align="left" content_margin_divider="true" hover_border_divider="true" mpc_icon__icon="ti ti-headphone" mpc_icon__icon_color="#ffffff" mpc_icon__icon_size="36" mpc_icon__background_color="#323232" mpc_icon__border_divider="true" mpc_icon__border_css="border-radius:60px;" mpc_icon__padding_divider="true" mpc_icon__padding_css="padding:15px;" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-right:20px;" mpc_icon__hover_background_color="#f53d03" mpc_icon__hover_border_divider="true" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__align="left" mpc_divider__content_border_divider="true" mpc_divider__content_padding_divider="true" mpc_divider__content_padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_divider__lines_color="#dddddd" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:3px;padding-bottom:3px;" mpc_divider__margin_divider="true"]Our Support Team is available 24 hours[/mpc_icon_column][/vc_column][vc_column width="1/3" css=".vc_custom_1517826736751{margin-bottom: 30px !important;}"][mpc_icon_column preset="mpc_preset_13" layout="style_3" alignment="left" padding_css="padding:0px;" title_font_color="#444444" title_font_size="18" title_font_line_height="1.4" title_font_transform="uppercase" title_font_align="left" title="30 Days Returns" title_margin_divider="true" title_margin_css="margin-bottom:5px;" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" content_font_align="left" mpc_icon__preset="mpc_preset_9" mpc_icon__icon="ti ti-reload" mpc_icon__icon_color="#ffffff" mpc_icon__icon_size="36" mpc_icon__background_color="#323232" mpc_icon__border_divider="true" mpc_icon__border_css="border-radius:60px;" mpc_icon__padding_css="padding:15px;" mpc_icon__margin_divider="true" mpc_icon__margin_css="margin-right:20px;" mpc_icon__hover_background_color="#f53d03" mpc_icon__hover_border_divider="true" mpc_divider__disable="true" mpc_divider__width="10" mpc_divider__align="left" mpc_divider__content_padding_divider="true" mpc_divider__content_padding_css="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;" mpc_divider__lines_color="#dddddd" mpc_divider__padding_divider="true" mpc_divider__padding_css="padding-top:3px;padding-bottom:3px;"]Product any fault within 30 days for an exchange.</p>
<p>[/mpc_icon_column][/vc_column][/vc_row]
CONTENT
);