<?php
//About Banner
return array(
	'name'             => esc_html__( 'Product Categories', 'ciyashop' ),
	'template_category'=> esc_html__( 'Product', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row pgscore_enable_responsive_settings="true" el_id="1515418069406-ab5d8d7e-54ac" css=".vc_custom_1525153303306{margin-top: 80px !important;margin-bottom: 40px !important;}" element_css_sm=".vc_custom_1525153303314{margin-top: 50px !important;margin-bottom: 20px !important;}" element_css_xs=".vc_custom_1525153303319{margin-top: 40px !important;margin-bottom: 10px !important;}" element_css_md=".vc_custom_1525153303311{margin-top: 60px !important;margin-bottom: 20px !important;}"][vc_column css=".vc_custom_1516691105496{padding-top: 0px !important;}"][vc_row_inner][vc_column_inner offset="vc_col-lg-offset-2 vc_col-lg-8 vc_col-md-offset-1 vc_col-md-10 vc_col-sm-offset-0 vc_col-xs-12"][vc_custom_heading text="Product Categories" font_container="tag:h2|text_align:center" use_theme_fonts="yes" font_weight="700" text_transform="uppercase" css=".vc_custom_1516691623437{margin-bottom: 20px !important;}"][vc_custom_heading text="Lorem ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy nibh euismod tincidunt ut laoree Dolore magna aliquam erat volutpat." font_container="tag:p|text_align:center" use_theme_fonts="yes" css=".vc_custom_1516690898116{margin-bottom: 50px !important;}"][/vc_column_inner][/vc_row_inner][mpc_wc_carousel_categories carousel_preset="mpc_preset_5" rows="1" cols="3" gap="25" start_at="1" loop="true" orderby="title" height="410" inline_content="true" layout="title,count" alignment="center" margin_css="margin:30px;" count_phrase="Item" fx_effect="zoomIn" fx_scale="110" title_font_preset="mpc_preset_17" title_font_color="#ffffff" title_font_size="18" title_font_line_height="1.5" title_font_transform="uppercase" title_font_align="center" title_overflow="true" count_font_preset="mpc_preset_22" count_font_color="#ffffff" count_font_size="14" count_font_line_height="1.5" count_font_align="center" count_margin_divider="true" count_margin_css="margin-bottom:-7px;" background_color="rgba(212,0,244,0.9)" regular_padding_divider="true" regular_padding_css="padding-top:20px;padding-right:60px;padding-bottom:20px;padding-left:60px;" hover_layout="title,count" hover_alignment="center" hover_title_font_preset="mpc_preset_17" hover_title_font_color="#ffffff" hover_title_font_size="18" hover_title_font_line_height="1.5" hover_title_font_align="center" hover_count_font_preset="mpc_preset_22" hover_count_font_size="14" hover_count_font_line_height="1.5" hover_count_font_align="center" overlay_background_color="#0c0c0c" overlay_padding_divider="true" overlay_padding_css="padding-top:20px;padding-right:60px;padding-bottom:20px;padding-left:60px;" mpc_navigation__preset="preset_0" mpc_navigation__padding_divider="true" include="90, 91, 92, 93"][/vc_column][/vc_row]
CONTENT
);