<?php
//About Banner
return array(
	'name'             => esc_html__( 'Product Showcase', 'ciyashop' ),
	'template_category'=> esc_html__( 'Product', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row pgscore_enable_responsive_settings="true" el_id="1509704023813-deff0b92-6683" css=".vc_custom_1524837018092{padding-top: 80px !important;padding-bottom: 40px !important;}" element_css_md=".vc_custom_1524837018096{padding-top: 60px !important;padding-bottom: 20px !important;}" element_css_sm=".vc_custom_1524837018099{padding-top: 50px !important;padding-bottom: 10px !important;}" element_css_xs=".vc_custom_1524837018101{padding-top: 40px !important;}"][vc_column css=".vc_custom_1509705321986{padding-top: 0px !important;padding-bottom: 40px !important;}" offset="vc_col-lg-4 vc_col-md-4"][vc_custom_heading text="Featured Product" font_container="tag:h6|text_align:left" use_theme_fonts="yes" font_weight="600" text_transform="uppercase" css=".vc_custom_1524837063309{margin-bottom: 20px !important;border-bottom-width: 1px !important;padding-bottom: 10px !important;border-bottom-color: #e8ebf1 !important;border-bottom-style: solid !important;}"][pgscore_product_showcase product_type="featured-products" number_of_item="12"][/vc_column][vc_column css=".vc_custom_1509705328275{padding-top: 0px !important;padding-bottom: 40px !important;}" offset="vc_col-lg-4 vc_col-md-4"][vc_custom_heading text="Sale Products" font_container="tag:h6|text_align:left" use_theme_fonts="yes" font_weight="600" text_transform="uppercase" css=".vc_custom_1524837073157{margin-bottom: 20px !important;border-bottom-width: 1px !important;padding-bottom: 10px !important;border-bottom-color: #e8ebf1 !important;border-bottom-style: solid !important;}"][pgscore_product_showcase product_type="products-in-sale" number_of_item="12"][/vc_column][vc_column css=".vc_custom_1509705333685{padding-top: 0px !important;padding-bottom: 40px !important;}" offset="vc_col-lg-4 vc_col-md-4"][vc_custom_heading text="Top Rated Products" font_container="tag:h6|text_align:left" use_theme_fonts="yes" font_weight="600" text_transform="uppercase" css=".vc_custom_1524837082757{margin-bottom: 20px !important;border-bottom-width: 1px !important;padding-bottom: 10px !important;border-bottom-color: #e8ebf1 !important;border-bottom-style: solid !important;}"][pgscore_product_showcase product_type="top-rated-products" number_of_item="12"][/vc_column][/vc_row]
CONTENT
);