<?php
//About Banner
return array(
	'name'             => esc_html__( 'Services Left Right Box 2', 'ciyashop' ),
	'template_category'=> esc_html__( 'Services', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row full_width="stretch_row" equal_height="yes" content_placement="middle" pgscore_enable_responsive_settings="true" el_id="1520926123822-8376791b-2113" css=".vc_custom_1524224728158{padding-top: 80px !important;padding-bottom: 80px !important;background: #f5f5f5 url(http://ciyashop.potenzaglobalsolutions.com/perfume/wp-content/uploads/sites/7/2018/03/bg-patten.jpg?id=659) !important;background-position: 0 0 !important;background-repeat: repeat !important;}" element_css_md=".vc_custom_1524224728161{padding-top: 60px !important;padding-bottom: 60px !important;}" element_css_sm=".vc_custom_1524224728164{padding-top: 50px !important;padding-bottom: 50px !important;}" element_css_xs=".vc_custom_1524224728166{padding-top: 40px !important;padding-bottom: 40px !important;}"][vc_column css=".vc_custom_1520926398291{padding-top: 0px !important;}"][vc_row_inner equal_height="yes" content_placement="middle" css=".vc_custom_1521203675595{margin-bottom: 30px !important;}"][vc_column_inner width="1/2"][vc_single_image source="external_link" custom_src="http://ciyashop.potenzaglobalsolutions.com/perfume/wp-content/uploads/sites/7/2018/03/about-img1.jpg"][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1524224528031{margin-right: 15px !important;margin-left: 15px !important;padding-top: 30px !important;padding-right: 8% !important;padding-bottom: 30px !important;padding-left: 8% !important;background-color: #ffffff !important;}"][vc_custom_heading text="New Perfumes" font_container="tag:h3|text_align:center" use_theme_fonts="yes"][vc_column_text css=".vc_custom_1521024425576{margin-bottom: 20px !important;}"]</p>
<p style="text-align: center;"><i style="text-align: center; font-size: 16px;">Resources Underprivileged</i></p>
<p>[/vc_column_text][mpc_divider preset="mpc_preset_6" width="32" content_type="icon" content_padding_divider="true" content_padding_css="padding-top:0px;padding-right:10px;padding-bottom:0px;padding-left:10px;" icon="etl etl-genius" icon_color="#e32a53" icon_size="24" lines_color="#e32a53" margin_divider="true" margin_css="margin-bottom:20px;"][vc_column_text css=".vc_custom_1521025337726{margin-bottom: 0px !important;}"]</p>
<p style="text-align: center;">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
<p>[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner equal_height="yes" content_placement="middle"][vc_column_inner el_class="order-md-2" width="1/2"][vc_single_image source="external_link" custom_src="http://ciyashop.potenzaglobalsolutions.com/perfume/wp-content/uploads/sites/7/2018/03/about-img2.jpg"][/vc_column_inner][vc_column_inner el_class="order-md-1" width="1/2" css=".vc_custom_1524224541718{margin-right: 15px !important;margin-left: 15px !important;padding-top: 30px !important;padding-right: 8% !important;padding-bottom: 30px !important;padding-left: 8% !important;background-color: #ffffff !important;}"][vc_custom_heading text="Top Perfumes" font_container="tag:h3|text_align:center" use_theme_fonts="yes"][vc_column_text css=".vc_custom_1521026213780{margin-bottom: 20px !important;}"]</p>
<p style="text-align: center;">Social Innovation legal</p>
<p>[/vc_column_text][mpc_divider preset="mpc_preset_6" width="32" content_type="icon" content_padding_divider="true" content_padding_css="padding-top:0px;padding-right:10px;padding-bottom:0px;padding-left:10px;" icon="etl etl-genius" icon_color="#e32a53" icon_size="24" lines_color="#e32a53" margin_divider="true" margin_css="margin-bottom:20px;"][vc_column_text css=".vc_custom_1521025337726{margin-bottom: 0px !important;}"]</p>
<p style="text-align: center;">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
<p>[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]
CONTENT
);