<?php
//About Banner
return array(
	'name'             => esc_html__( 'Video with Opening Hours', 'ciyashop' ),
	'template_category'=> esc_html__( 'Video', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row full_width="stretch_row" equal_height="yes" pgscore_bg_type="row-background-dark" pgscore_background_position="center-center" enable_first_overlay="true" first_overlay_opacity="85" first_background_color="#d400f4" pgscore_enable_responsive_settings="true" el_id="1516714650614-81e0de0a-afcf" css=".vc_custom_1524834002725{padding-top: 80px !important;padding-bottom: 50px !important;background-image: url(http://ciyashop.potenzaglobalsolutions.com/shisha/wp-content/uploads/2018/01/section-bg.jpg?id=12173) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" element_css_sm=".vc_custom_1524834002732{padding-top: 60px !important;padding-bottom: 30px !important;}" element_css_xs=".vc_custom_1524834002735{padding-top: 40px !important;padding-bottom: 10px !important;}"][vc_column css=".vc_custom_1518248161219{margin-bottom: 30px !important;padding-top: 0px !important;}" offset="vc_col-lg-8 vc_col-md-7"][vc_video link="https://vimeo.com/16326937" css=".vc_custom_1516769928057{margin-bottom: 0px !important;}"][/vc_column][vc_column css=".vc_custom_1518248301482{margin-right: 15px !important;margin-bottom: 30px !important;margin-left: 15px !important;border-top-width: 12px !important;border-right-width: 12px !important;border-bottom-width: 12px !important;border-left-width: 12px !important;padding-top: 35px !important;padding-right: 15px !important;padding-bottom: 35px !important;padding-left: 15px !important;border-left-color: #ffffff !important;border-left-style: solid !important;border-right-color: #ffffff !important;border-right-style: solid !important;border-top-color: #ffffff !important;border-top-style: solid !important;border-bottom-color: #ffffff !important;border-bottom-style: solid !important;}" el_class="icon-light" offset="vc_col-lg-4 vc_col-md-5"][vc_custom_heading text="Opening Times" font_container="tag:h4|text_align:left" use_theme_fonts="yes" font_weight="700" css=".vc_custom_1516770536956{margin-bottom: 30px !important;}"][pgscore_opening_hours][/vc_column][/vc_row]
CONTENT
);