<?php
//About Banner
return array(
	'name'             => esc_html__( 'Video With Info', 'ciyashop' ),
	'template_category'=> esc_html__( 'Video', 'ciyashop' ),
	'disabled'         => true,                                        // Disable it to not show in the default tab
	'content'          => <<<CONTENT
[vc_row full_width="stretch_row" equal_height="yes" content_placement="top" pgscore_enable_responsive_settings="true" el_id="1523966087888-64cb7801-9adf" css=".vc_custom_1533541136259{padding-top: 80px !important;padding-bottom: 20px !important;}" element_css_md=".vc_custom_1533541136261{padding-top: 60px !important;padding-bottom: 30px !important;}" element_css_sm=".vc_custom_1533541136262{padding-top: 50px !important;padding-bottom: 20px !important;}" element_css_xs=".vc_custom_1533541136263{padding-top: 40px !important;padding-bottom: 10px !important;}"][vc_column css=".vc_custom_1524054906027{margin-bottom: 30px !important;padding-top: 0px !important;}" offset="vc_col-lg-6 vc_col-md-6"][vc_video link="https://www.youtube.com/watch?v=g00amCRP_Uk"][/vc_column][vc_column css=".vc_custom_1524054915585{margin-bottom: 30px !important;padding-top: 0px !important;}" offset="vc_col-lg-6 vc_col-md-6"][vc_custom_heading text="Quality & Reliable" use_theme_fonts="yes" css=".vc_custom_1523968313758{margin-bottom: 20px !important;}"][vc_column_text css=".vc_custom_1533646156053{margin-bottom: 20px !important;}"]I truly believe Augustine’s words are true and if you look at history you know it is true. There are many people in the world with amazing talents.[/vc_column_text][mpc_icon_column layout="style_3" alignment="left" title_font_preset="preset_0" title_font_color="#444444" title_font_size="20" title_font_line_height="1.4" title_font_transform="none" title_font_align="left" title="100% Pure Leather" title_margin_divider="true" title_margin_css="margin-left:20px;" content_font_preset="preset_0" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" content_font_transform="none" content_font_align="left" content_margin_divider="true" content_margin_css="margin-left:20px;" mpc_icon__icon_type="image" mpc_icon__icon_image="488" mpc_icon__border_divider="true" mpc_divider__disable="true"]Commitment – understanding the price
and having the willingness to pay that price[/mpc_icon_column][vc_empty_space height="30px"][mpc_icon_column layout="style_3" alignment="left" title_font_preset="preset_0" title_font_color="#444444" title_font_size="20" title_font_line_height="1.4" title_font_transform="none" title_font_align="left" title="Free Delivery" title_margin_divider="true" title_margin_css="margin-left:20px;" content_font_preset="preset_0" content_font_color="#888888" content_font_size="14" content_font_line_height="1.5" content_font_transform="none" content_font_align="left" content_margin_divider="true" content_margin_css="margin-left:20px;" mpc_icon__icon_type="image" mpc_icon__icon_image="489" mpc_icon__border_divider="true" mpc_divider__disable="true"]If success is a process with a number
of defined steps, then it is just like[/mpc_icon_column][/vc_column][/vc_row]
CONTENT
);