<?php
return array(

	// About
	'kite-box',
	'about-left-parallax',
	'about-right-parallax',
	'about-skill-parallax',
	'about-image-left-style1',
	'about-image-left-style2',
	'about-image-left-style3',
	'about-image-left-style4',
	'about-image-left-style5',
	'about-image-left-style6',
	'about-with-center-image',
	'about-with-center-image2',
	'about-with-center-image3',
	'payment-info-with-image',
	'about-jewellery',
	'process-steps-left-right',
	'about-with-skill-gallery',
	'about-with-tab',
	'about-with-accordion',
	'about-with-tab-faq',
	'about-with-counter',
	'about-with-counter2',
	'about-kids-category',
	'about-image-popup',
	'about-info-with-signature',
	'about-info-with-signature2',
	'about-info-with-signature3',
	'about-info-with-signature4',
	'about-info-with-signature5',
	'about-info-with-signature6',
	'about-info-with-social',
	'about-info-with-skill',
	'about-info-with-skill2',
	'about-skill-bg-image',
	'about-info-with-list',
	'about-with-4-image',
	'about-kids-info',
	'about-product-info',
	'about-info-counter-style',
	'about-service',
	'top-image-with-content',
	'about-with-info-box',
	'about-with-info-box2',
	'right-image-with-numeric-info',


	// Action Box
	'action-box-full-bg',
	'action-box-with-border',
	'action-box-image-color-overlay',
	'action-box-bg-image',
	'action-box-bg-image-2',

	// Banner
	'banner-3-left-categories',
	'banner-5-images',
	'banner-4-images',
	'banner-3-images',
	'banner-2-images',
	'banner-2-images-style2',
	'banner-2-images-style3',
	'banner-3-images-style2',
	'banner-3-images-style3',
	'banner-3-images-style4',
	'banner-4-images-style2',
	'banner-4-images-style3',
	'banner-with-info',

	// Blog
	'blog-style1',
	'blog-style2',
	'blog-style3',
	'blog-style1-with-intro',
	'blog-style3-with-intro',

	// Brand
	'brand-with-left-info',
	'brand-with-slider',
	'brand-left-image',
	'brand-with-skill',
	'brand-with-action-box',
	'brand-newslatter-instagram',
	'brand-6-grid-dark-bg',

	// Contact Info
	'contact-info-style1',
	'contact-info-style2',
	'contact-info-style3',
	'contact-info-style4',
	'contact-info-style5',
	'contact-info-style6',
	'contact-info-style7',
	'contact-info-style8',
	'contact-info-style9',
	'contact-info-style10',
	'contact-info-style11',

	// Counter
	'counter-only-number',
	'counter-only-number2',
	'counter-top-icon',
	'counter-with-skill-image',
	'counter-in-square',
	'counter-top-icon-rounded',
	'counter-with-border',
	'counter-with-info',
	'counter-with-top-info',

	// Form
	'form-right-bg-image',
	'form-right-bg-image2',
	'form-right-contact-info',
	'form-right-bottom-info',
	'form-with-map',
	'form-blue-bg-with-pattern',
	'form-dark-bg-with-info',
	'form-with-content',
	'top-map-with-from',
	'from-with-contact-info',

	// Hotspots
	'hotspots-electronic',
	'hotspots-bicycle',
	'hotspots-furniture',
	'hotspots-plumbing',
	'hotspots-landing-shoes',
	'weapon-hotspots',

	// Feature Box
	'iconbox-bg-image-overlay',
	'iconbox-6-reasons',
	'iconbox-6-reasons-2',
	'iconbox-6-reasons-3',
	'iconbox-dark-bg-overlay',
	'iconbox-left-big-image',
	'iconbox-with-6-box',
	'iconbox-bg-image-bottom',
	'iconbox-with-icon-border',
	'iconbox-with-video-popup',
	'iconbox-with-video-popup2',
	'iconbox-with-bg-image',
	'iconbox-left-BG-image',
	'iconbox-with-right-info',
	'iconbox-3box-with-pattern',

	// Info Box
	'infobox-4-info-box-border',
	'infobox-4-info-box-flat',
	'infobox-3-top-center-border',
	'infobox-3-different-color',
	'infobox-with-number-bg',
	'infobox-theme-bg-with-button',
	'infobox-grey-bg-with-border',
	'infobox-rounded-icon-in-dark-bg',
	'infobox-pattern-bg-border',
	'infobox-with-bg-style-1',
	'infobox-with-bg-style-2',
	'infobox-3-with-white-bg',
	'infobox-3-with-dark-bg',
	'infobox-full-with-dark-bg',
	'infobox-with-top-info',
	'infobox-full-with-border',

	// Product
	'product-showcase',
	'product-showcase-with-banner',
	'product-showcase-with-banner2',
	'product-look-book',
	'product-info',
	'product-categories',
	'product-categories-2',
	'product-categories-list-image',
	'product-categories-list-image2',
	'product-deal-left-intro',
	'product-left-right-info',
	'product-white-bg-with-image',
	'product-white-bg-with-image2',
	'custom-product-categories',
	'product-with-banner',
	

	// Services
	'services-theme-bg-pattern',
	'services-bg-image-overlay',
	'services-bg-image-3box',
	'services-with-3box',
	'services-with-4box',
	'services-with-6box',
	'services-with-6box-2',
	'services-with-icon-box',
	'services-left-right-info',
	'services-left-right-info2',
	'services-left-right-info3',
	'services-left-right-info4',
	'services-box-with-bg',
	'services-box-with-bg2',
	'services-image-with-content',
	'left-image-with-service',

	// Testimonial
	'testimonial-dark-bg-full-style1',
	'testimonial-dark-bg-full-style3',
	'testimonial-left-bg-image-style1',
	'testimonial-full-bg-image-style1',
	'testimonial-light-bg-style1',
	'testimonial-light-bg-style2',
	'testimonial-dark-bg-style1',
	'testimonial-with-deals-products',
	'testimonial-with-skill',
	'testimonial-with-skill2',
	'testimonial-with-brand',
	'testimonial-with-info',
	'customer-reviews',

	// Video
	'video-with-right-info',
	'video-with-icon-on-top',
	'video-with-opening-hours',
	'video-with-product-details',
	'video-with-content',
	'background-image-with-video',
	'video-with-info',

);